services:
  postgres16:
    image: 'postgres:16-alpine'
    environment:
      POSTGRES_DB: SCHOOL
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: salman
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: